apiVersion: apps/v1
kind: Deployment

metadata:
  name: agrocd-demo

spec:
  replicas: 6

  selector:
    matchLabels:
      app: agrocd-demo

  template:
    metadata:
      labels:
        app: agrocd-demo

    spec:
      containers:
        - name: agrocd-demo
          image: ghcr.io/derryman101/agrocd-demo:7e48da1c4e1470cabfc28976b69ae3d33a2abfe3
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3001
