apiVersion: apps/v1
kind: Deployment

metadata:
  name: agrocd-demo

spec:
  replicas: 6

  selector:
    matchLabels:
      app: agrocd-demo

  template:
    metadata:
      labels:
        app: agrocd-demo

    spec:
      containers:
        - name: agrocd-demo
          image: ghcr.io/derryman101/agrocd-demo:863ee842d7da79b8773b596b6c710e344733ccad
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3001
